"""
Blockchain integration service.
Bridges the BattleRoyale smart contract with the backend.

In DEV_MODE, all on-chain operations are simulated (no real transactions).
In production, requires:
  - RPC_URL pointing to Base/Polygon
  - BATTLE_ROYALE_CONTRACT_ADDRESS deployed contract
  - OPERATOR_PRIVATE_KEY to sign operator transactions
  - USDC_ADDRESS on the target chain
"""
from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Optional

from backend.config import settings

logger = logging.getLogger(__name__)

# Minimal ABI — only the functions we call from the backend.
# Full ABI is generated by Hardhat/Foundry compilation.
BATTLE_ROYALE_ABI = [
    {
        "inputs": [{"name": "maxPlayers", "type": "uint32"}],
        "name": "createMatch",
        "outputs": [{"name": "matchId", "type": "uint256"}],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [{"name": "matchId", "type": "uint256"}],
        "name": "lockMatch",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"name": "matchId", "type": "uint256"},
            {"name": "winner", "type": "address"},
        ],
        "name": "declareWinner",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [{"name": "matchId", "type": "uint256"}],
        "name": "cancelMatch",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [{"name": "matchId", "type": "uint256"}],
        "name": "claimPrize",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [{"name": "matchId", "type": "uint256"}],
        "name": "claimRefund",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [{"name": "matchId", "type": "uint256"}],
        "name": "getMatch",
        "outputs": [
            {
                "components": [
                    {"name": "status", "type": "uint8"},
                    {"name": "prizePool", "type": "uint256"},
                    {"name": "winner", "type": "address"},
                    {"name": "playerCount", "type": "uint32"},
                    {"name": "maxPlayers", "type": "uint32"},
                ],
                "name": "",
                "type": "tuple",
            }
        ],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"name": "matchId", "type": "uint256"}],
        "name": "getNetPayout",
        "outputs": [{"name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "ENTRY_FEE",
        "outputs": [{"name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [
            {"name": "", "type": "uint256"},
            {"name": "", "type": "address"},
        ],
        "name": "hasJoined",
        "outputs": [{"name": "", "type": "bool"}],
        "stateMutability": "view",
        "type": "function",
    },
]

# USDC ERC-20 minimal ABI for balance/allowance checks
USDC_ABI = [
    {
        "inputs": [{"name": "account", "type": "address"}],
        "name": "balanceOf",
        "outputs": [{"name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [
            {"name": "owner", "type": "address"},
            {"name": "spender", "type": "address"},
        ],
        "name": "allowance",
        "outputs": [{"name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
]

ENTRY_FEE_USDC = 10_000_000  # 10 USDC (6 decimals)


@dataclass
class ChainMatchInfo:
    chain_match_id: int
    status: str  # Open, Locked, Finished, Cancelled
    prize_pool_usdc: float
    player_count: int
    winner: Optional[str]
    net_payout_usdc: float


@dataclass
class TxResult:
    success: bool
    tx_hash: Optional[str]
    chain_match_id: Optional[int] = None
    error: Optional[str] = None


# Match status enum from contract
_STATUS_MAP = {0: "Open", 1: "Locked", 2: "Finished", 3: "Cancelled"}


class BlockchainService:
    """
    Handles all smart contract interactions.
    In DEV_MODE, simulates everything locally.
    """

    def __init__(self):
        self._dev_mode = settings.DEV_MODE
        self._w3 = None
        self._contract = None
        self._usdc = None
        self._operator_account = None
        self._dev_match_counter = 0
        self._dev_matches: dict[int, dict] = {}

        if not self._dev_mode:
            self._init_web3()

    def _init_web3(self):
        """Initialize Web3 connection and contract instances."""
        try:
            from web3 import Web3
            from web3.middleware import ExtraDataToPOAMiddleware

            self._w3 = Web3(Web3.HTTPProvider(settings.RPC_URL))

            # PoA chains (Polygon, Base) need this middleware
            self._w3.middleware_onion.inject(ExtraDataToPOAMiddleware, layer=0)

            if not self._w3.is_connected():
                logger.error("Web3: Cannot connect to %s", settings.RPC_URL)
                return

            if settings.BATTLE_ROYALE_CONTRACT_ADDRESS:
                self._contract = self._w3.eth.contract(
                    address=Web3.to_checksum_address(settings.BATTLE_ROYALE_CONTRACT_ADDRESS),
                    abi=BATTLE_ROYALE_ABI,
                )
            else:
                logger.warning("BATTLE_ROYALE_CONTRACT_ADDRESS not set — on-chain ops disabled")

            if settings.USDC_ADDRESS:
                self._usdc = self._w3.eth.contract(
                    address=Web3.to_checksum_address(settings.USDC_ADDRESS),
                    abi=USDC_ABI,
                )

            if settings.OPERATOR_PRIVATE_KEY:
                self._operator_account = self._w3.eth.account.from_key(
                    settings.OPERATOR_PRIVATE_KEY
                )
                logger.info(
                    "Blockchain: connected to %s, operator=%s",
                    settings.RPC_URL,
                    self._operator_account.address,
                )
            else:
                logger.warning("OPERATOR_PRIVATE_KEY not set — cannot sign transactions")

        except ImportError:
            logger.warning("web3 not installed — blockchain features disabled")
            self._dev_mode = True
        except Exception as e:
            logger.error("Web3 init failed: %s", e)
            self._dev_mode = True

    @property
    def is_live(self) -> bool:
        """True if we have a real blockchain connection."""
        return (
            not self._dev_mode
            and self._w3 is not None
            and self._contract is not None
            and self._operator_account is not None
        )

    # ── Operator actions ──────────────────────────────────────────────────────

    async def create_match_onchain(self, max_players: int) -> TxResult:
        """Create a match on the smart contract."""
        if self._dev_mode:
            self._dev_match_counter += 1
            mid = self._dev_match_counter
            self._dev_matches[mid] = {
                "status": "Open",
                "prize_pool": 0,
                "player_count": 0,
                "winner": None,
                "max_players": max_players,
            }
            logger.info("[DEV] createMatch(%d) → chain_match_id=%d", max_players, mid)
            return TxResult(success=True, tx_hash=f"0x{'de'*32}", chain_match_id=mid)

        return await self._send_operator_tx(
            self._contract.functions.createMatch(max_players)
        )

    async def lock_match_onchain(self, chain_match_id: int) -> TxResult:
        """Lock a match roster on-chain."""
        if self._dev_mode:
            m = self._dev_matches.get(chain_match_id)
            if m:
                m["status"] = "Locked"
            logger.info("[DEV] lockMatch(%d)", chain_match_id)
            return TxResult(success=True, tx_hash=f"0x{'de'*32}", chain_match_id=chain_match_id)

        return await self._send_operator_tx(
            self._contract.functions.lockMatch(chain_match_id)
        )

    async def declare_winner_onchain(
        self, chain_match_id: int, winner_wallet: str
    ) -> TxResult:
        """Declare match winner on-chain. Winner can then call claimPrize()."""
        if self._dev_mode:
            m = self._dev_matches.get(chain_match_id)
            if m:
                m["status"] = "Finished"
                m["winner"] = winner_wallet
            logger.info("[DEV] declareWinner(%d, %s)", chain_match_id, winner_wallet)
            return TxResult(success=True, tx_hash=f"0x{'de'*32}", chain_match_id=chain_match_id)

        from web3 import Web3

        return await self._send_operator_tx(
            self._contract.functions.declareWinner(
                chain_match_id,
                Web3.to_checksum_address(winner_wallet),
            )
        )

    async def cancel_match_onchain(self, chain_match_id: int) -> TxResult:
        """Cancel a match on-chain. Participants can then claim refunds."""
        if self._dev_mode:
            m = self._dev_matches.get(chain_match_id)
            if m:
                m["status"] = "Cancelled"
            logger.info("[DEV] cancelMatch(%d)", chain_match_id)
            return TxResult(success=True, tx_hash=f"0x{'de'*32}", chain_match_id=chain_match_id)

        return await self._send_operator_tx(
            self._contract.functions.cancelMatch(chain_match_id)
        )

    # ── Read-only queries ─────────────────────────────────────────────────────

    async def get_match_info(self, chain_match_id: int) -> Optional[ChainMatchInfo]:
        """Read match state from the contract."""
        if self._dev_mode:
            m = self._dev_matches.get(chain_match_id)
            if not m:
                return None
            return ChainMatchInfo(
                chain_match_id=chain_match_id,
                status=m["status"],
                prize_pool_usdc=m["prize_pool"] / 1e6,
                player_count=m["player_count"],
                winner=m["winner"],
                net_payout_usdc=m["prize_pool"] / 1e6,
            )

        try:
            result = self._contract.functions.getMatch(chain_match_id).call()
            payout = self._contract.functions.getNetPayout(chain_match_id).call()
            return ChainMatchInfo(
                chain_match_id=chain_match_id,
                status=_STATUS_MAP.get(result[0], "Unknown"),
                prize_pool_usdc=result[1] / 1e6,
                player_count=result[3],
                winner=result[2] if result[2] != "0x" + "0" * 40 else None,
                net_payout_usdc=payout / 1e6,
            )
        except Exception as e:
            logger.error("getMatch(%d) failed: %s", chain_match_id, e)
            return None

    async def check_usdc_balance(self, wallet: str) -> float:
        """Check USDC balance for a wallet (returns human-readable amount)."""
        if self._dev_mode:
            return 1000.0  # Dev mode: everyone has 1000 USDC

        if not self._usdc:
            return 0.0

        try:
            from web3 import Web3

            balance = self._usdc.functions.balanceOf(
                Web3.to_checksum_address(wallet)
            ).call()
            return balance / 1e6
        except Exception as e:
            logger.error("balanceOf(%s) failed: %s", wallet, e)
            return 0.0

    async def check_usdc_allowance(self, wallet: str) -> float:
        """Check how much USDC the wallet has approved for the contract."""
        if self._dev_mode:
            return 1000.0

        if not self._usdc or not self._contract:
            return 0.0

        try:
            from web3 import Web3

            allowance = self._usdc.functions.allowance(
                Web3.to_checksum_address(wallet),
                self._contract.address,
            ).call()
            return allowance / 1e6
        except Exception as e:
            logger.error("allowance(%s) failed: %s", wallet, e)
            return 0.0

    async def has_joined_onchain(self, chain_match_id: int, wallet: str) -> bool:
        """Check if wallet has joined the match on-chain."""
        if self._dev_mode:
            return False

        try:
            from web3 import Web3

            return self._contract.functions.hasJoined(
                chain_match_id,
                Web3.to_checksum_address(wallet),
            ).call()
        except Exception as e:
            logger.error("hasJoined(%d, %s) failed: %s", chain_match_id, wallet, e)
            return False

    # ── Internal ──────────────────────────────────────────────────────────────

    async def _send_operator_tx(self, func) -> TxResult:
        """Build, sign, and send an operator transaction."""
        try:
            tx = func.build_transaction(
                {
                    "from": self._operator_account.address,
                    "nonce": self._w3.eth.get_transaction_count(
                        self._operator_account.address
                    ),
                    "gas": 300_000,
                    "maxFeePerGas": self._w3.eth.gas_price * 2,
                    "maxPriorityFeePerGas": self._w3.to_wei(1, "gwei"),
                }
            )
            signed = self._w3.eth.account.sign_transaction(
                tx, self._operator_account.key
            )
            tx_hash = self._w3.eth.send_raw_transaction(signed.raw_transaction)
            receipt = self._w3.eth.wait_for_transaction_receipt(tx_hash, timeout=60)

            if receipt["status"] == 1:
                logger.info("TX success: %s", tx_hash.hex())
                return TxResult(success=True, tx_hash=tx_hash.hex())
            else:
                logger.error("TX reverted: %s", tx_hash.hex())
                return TxResult(success=False, tx_hash=tx_hash.hex(), error="Transaction reverted")
        except Exception as e:
            logger.error("TX failed: %s", e)
            return TxResult(success=False, tx_hash=None, error=str(e))


# Global singleton
blockchain = BlockchainService()
